version: '3.8'

networks:
  summiva-network-prod:
    driver: bridge

services:
  backend:
    image: backend:latest
    environment:
      - ENVIRONMENT=production
      - SERVICE_NAME=backend
      - PYTHONPATH=/app/src
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-summiva}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    networks:
      - summiva-network-prod
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  auth:
    image: auth:latest
    environment:
      - ENVIRONMENT=production
      - SERVICE_NAME=auth
      - PYTHONPATH=/app/src
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-summiva}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - summiva-network-prod
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  summarization:
    image: summarization:latest
    environment:
      - ENVIRONMENT=production
      - SERVICE_NAME=summarization
      - PYTHONPATH=/app/src
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    networks:
      - summiva-network-prod
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  tagging:
    image: tagging:latest
    environment:
      - ENVIRONMENT=production
      - SERVICE_NAME=tagging
      - PYTHONPATH=/app/src
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    networks:
      - summiva-network-prod
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  grouping:
    image: grouping:latest
    environment:
      - ENVIRONMENT=production
      - SERVICE_NAME=grouping
      - PYTHONPATH=/app/src
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    networks:
      - summiva-network-prod
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  search:
    image: search:latest
    environment:
      - ENVIRONMENT=production
      - SERVICE_NAME=search
      - PYTHONPATH=/app/src
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    networks:
      - summiva-network-prod
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  clustering:
    image: clustering:latest
    environment:
      - ENVIRONMENT=production
      - SERVICE_NAME=clustering
      - PYTHONPATH=/app/src
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    networks:
      - summiva-network-prod
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-summiva}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - summiva-network-prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    networks:
      - summiva-network-prod
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:6
    volumes:
      - mongodb_data:/data/db
    networks:
      - summiva-network-prod
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./infra/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - summiva-network-prod
    entrypoint: ["/etc/prometheus/entrypoint.sh"]
    # Using entrypoint script instead of command
    # command is defined in the entrypoint script
    depends_on:
      - backend
      - auth
      - summarization
      - tagging
      - grouping
      - search
      - clustering

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - summiva-network-prod
    depends_on:
      - prometheus

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  mongodb_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local