# summiva/docker-compose.yml
services:
  # --- Auth Service & DB ---
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: summiva-auth-service
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://summiva_user:summiva_pass@auth_postgresql/summiva_db
      JWT_SECRET_KEY: your_jwt_secret_key_here
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    depends_on:
      auth_postgresql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - summiva-net

  auth_postgresql:
    image: postgres:16
    container_name: summiva_auth_postgresql
    ports:
      - "5433:5432"  # avoid conflict
    environment:
      POSTGRES_USER: summiva_user
      POSTGRES_PASSWORD: summiva_pass
      POSTGRES_DB: summiva_db
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U summiva_user -d summiva_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - summiva-net

  # --- Summarization Service ---
  summarization-service:
    build: ./summarization_service
    container_name: summarization_service_api
    ports:
      - "8001:8001"
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      AUTH_SERVICE_URL: http://auth-service:8000
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: rpc://
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      celery-worker:
        condition: service_healthy
      auth-service:
        condition: service_healthy
    networks:
      - summiva-net

  celery-worker:
    build: ./summarization_service
    container_name: summiva_celery_worker
    command: ["celery", "-A", "src.celery_tasks.worker.celery_app", "worker", "--loglevel=info"]
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      AUTH_SERVICE_URL: http://auth-service:8000
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: rpc://
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: [
        "CMD-SHELL",
        "celery -A src.celery_tasks.worker.celery_app inspect ping || exit 1"
      ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - summiva-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: summiva_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics ping || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - summiva-net

  mongodb:
    image: mongo:7.0
    container_name: summiva_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: [
        "CMD-SHELL",
        "mongosh --quiet --eval 'db.runCommand({ ping: 1 })' || exit 1"
      ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - summiva-net

volumes:
  auth_postgres_data:
  mongodb_data:

networks:
  summiva-net:
    name: summiva-net
