services:
  summarization-service:
    build: .
    ports:
      - "8001:8001"
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      AUTH_SERVICE_URL: http://localhost:8000
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: rpc://
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - summiva-net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - summiva-net

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    networks:
      - summiva-net

volumes:
  mongodb_data:

networks:
  summiva-net: