apiVersion: apps/v1
kind: Deployment
metadata:
  name: summiva-backend
  namespace: summiva
spec:
  replicas: 3
  selector:
    matchLabels:
      app: summiva-backend
  template:
    metadata:
      labels:
        app: summiva-backend
    spec:
      containers:
      - name: summiva-api
        image: summiva/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: summiva-config
              key: db_host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: summiva-config
              key: db_name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: summiva-secrets
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: summiva-secrets
              key: db_password
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config-volume
        configMap:
          name: backend-config

---
apiVersion: v1
kind: Service
metadata:
  name: summiva-backend
  namespace: summiva
spec:
  selector:
    app: summiva-backend
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer
