apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode yes
    port 6379
    timeout 0
    tcp-keepalive 300
    requirepass ${REDIS_PASSWORD}
    maxclients 10000
    maxmemory 500mb
    maxmemory-policy allkeys-lru
    rename-command FLUSHALL ""
    rename-command FLUSHDB ""
    rename-command CONFIG ""
    rename-command DEBUG ""

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  redis-password: c3VtbWl2YV9yZWRpc19wYXNzd29yZA== # Base64 encoded "summiva_redis_password"
