version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(filename)s:%(lineno)d | %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    formatter: standard
    filename: logs/application.log
    maxBytes: 5242880  # 5 MB
    backupCount: 5

  error_file:
    class: logging.handlers.RotatingFileHandler
    formatter: standard
    filename: logs/error.log
    maxBytes: 5242880
    backupCount: 5
    level: ERROR

root:
  level: DEBUG
  handlers: [console, file, error_file]

loggers:
  uvicorn.error:
    level: INFO
  uvicorn.access:
    level: WARNING
