global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "rules/*.yml"
  - "redis-security-rules.yml"

scrape_configs:
  # Scrape Prometheus server itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Specific job for Summiva FastAPI backend metrics
  - job_name: "summiva-backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["summiva-backend:8000"]
    honor_labels: true

  # Development environment - for local testing
  - job_name: "summiva-backend-dev"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:8000"]
    honor_labels: true

  # Scrape Kubernetes nodes (metrics like CPU, memory, disk)
  - job_name: "kubernetes-nodes"
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
  # Scrape all application pods (Summiva backend, frontend, etc.)
  - job_name: "kubernetes-pods"
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        
  # Redis monitoring
  - job_name: "redis"
    static_configs:
      - targets:
        - redis:6379
    metrics_path: /metrics
    scheme: http
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+):(?:\d+);(.+)
        replacement: $1:$2

  # Scrape kube-state-metrics (Kubernetes object states: deployments, pods, replicas)
  - job_name: "kube-state-metrics"
    static_configs:
      - targets: ["kube-state-metrics.kube-system.svc.cluster.local:8080"]

  # Scrape node-exporter (for detailed node metrics)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter.kube-system.svc.cluster.local:9100"]