name: summiva
description: An Enterprise-Scale NLP System for Content Summarization, Tagging, and Search
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  go_router: ^13.0.0
  flutter_markdown: ^0.6.18
  url_launcher: ^6.2.4
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  path: ^1.8.3
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/ 
