default:
  app_name: "Summiva Platform"
  version: "1.0"
  log_level: "INFO"
  jwt_algorithm: "HS256"
  access_token_expire_minutes: 60

  auth_service_url: "http://auth-service:8000"

  database:
    pool_size: 10
    max_overflow: 20

  postgres:
    uri: "postgresql://summiva_user:summiva_pass@postgresql/summiva_db"

  mongodb:
    uri: "mongodb://mongodb:27017"
    
  redis:
    host: "redis"
    port: 6379
    db: 0
    password: "summiva_redis_password"
    use_ssl: false

  celery:
    broker_url: "amqp://guest:guest@rabbitmq:5672//"
    result_backend: "rpc://"

  search:
    elastic_url: "http://elasticsearch:9200"
    faiss_index_path: "faiss/summiva.index"
    faiss_doc_map_path: "faiss/doc_ids.npy"

  log_config: "config/logging.conf"

  prometheus_port: 9090
  grafana_port: 3000

development:
  log_level: "DEBUG"
  auth_service_url: "http://localhost:8000"  # OK for dev testing UI
  postgres:
    uri: "postgresql://summiva_user:summiva_pass@postgres:5432/summiva_db"
  mongodb:
    uri: "mongodb://mongodb:27017"

production:
  log_level: "WARNING"
  auth_service_url: "https://auth.summiva.com"
  postgres:
    uri: "postgresql://summiva_user:summiva_pass@prod-db.internal/summiva_db"
  mongodb:
    uri: "mongodb://prod-mongo:27017"
  search:
    elastic_url: "http://prod-elasticsearch:9200"
    faiss_index_path: "/mnt/data/faiss.index"
    faiss_doc_map_path: "/mnt/data/doc_ids.npy"