services:

  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://summiva_user:summiva_pass@postgresql/summiva_db
      JWT_SECRET_KEY: your_jwt_secret_key_here
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    depends_on:
      - postgresql

  postgresql:
    image: postgres:16
    container_name: summiva_postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: summiva_user
      POSTGRES_PASSWORD: summiva_pass
      POSTGRES_DB: summiva_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
