version: '3.9'
services:
  auth-service:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://summiva_user:summiva_pass@auth_postgresql/summiva_db
      JWT_SECRET_KEY: your_jwt_secret_key_here
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    depends_on:
      auth_postgresql:
        condition: service_healthy
    networks:
      - summiva-net

  auth_postgresql:
    image: postgres:16
    environment:
      POSTGRES_USER: summiva_user
      POSTGRES_PASSWORD: summiva_pass
      POSTGRES_DB: summiva_db
    ports:
      - "5433:5432"
    networks:
      - summiva-net

volumes:
  auth_postgres_data:

networks:
  summiva-net:
